// deno-fmt-ignore
export const CatalogType = {
  movie:   'films',
  series:  'series',
  anime:   'animation',
  cartoon: 'cartoons',
  show:    'show',
  games:   'games',
} as const

// deno-fmt-ignore
export const URLType = {
  films:     'movie',
  series:    'series',
  animation: 'anime',
  cartoons:  'cartoon',
  show:      'show',
  games:     'games',
} as const

// deno-fmt-ignore
export const CatalogQueryType = {
  movie:   1,
  series:  2,
  cartoon: 3,
  anime:   82,
} as const

export const CatalogFilmGenres = [
  'action',
  'adventures',
  'arthouse',
  'biographical',
  'cognitive',
  'comedy',
  'concert',
  'crime',
  'detective',
  'documentary',
  'drama',
  'erotic',
  'family',
  'fantasy',
  'fiction',
  'foreign',
  'historical',
  'horror',
  'kids',
  'melodrama',
  'military',
  'musical',
  'musical',
  'russian',
  'short',
  'sport',
  'standup',
  'theatre',
  'thriller',
  'travel',
  'ukrainian',
  'western',
] as const

export const CatalogSeriesGenres = [
  'action',
  'adventures',
  'arthouse',
  'biographical',
  'comedy',
  'crime',
  'detective',
  'documentary',
  'drama',
  'erotic',
  'family',
  'fantasy',
  'fiction',
  'foreign',
  'historical',
  'horror',
  'melodrama',
  'military',
  'musical',
  'realtv',
  'russian',
  'sport',
  'standup',
  'telecasts',
  'thriller',
  'ukrainian',
  'western',
] as const

export const CatalogCartoonsGenres = [
  'action',
  'adult',
  'adventures',
  'anime',
  'arthouse',
  'biographical',
  'cognitive',
  'comedy',
  'crime',
  'detective',
  'documentary',
  'drama',
  'erotic',
  'fairytale',
  'family',
  'fantasy',
  'fiction',
  'foreign',
  'full-length',
  'historical',
  'horror',
  'kids',
  'melodrama',
  'military',
  'multseries',
  'musical',
  'russian',
  'short',
  'soyzmyltfilm',
  'sport',
  'thriller',
  'ukrainian',
  'western',
] as const

export const CatalogAnimationGenres = [
  'action',
  'adventures',
  'comedy',
  'detective',
  'drama',
  'ecchi',
  'educational',
  'erotic',
  'everyday',
  'fairytale',
  'fantasy',
  'fiction',
  'fighting',
  'historical',
  'horror',
  'kids',
  'kodomo',
  'mahoushoujo',
  'mecha',
  'military',
  'musical',
  'mystery',
  'parody',
  'romance',
  'samurai',
  'school',
  'shoujo',
  'shoujoai',
  'shounen',
  'shounenai',
  'sport',
  'thriller',
] as const

/*
export const genres = {
  'action': 'боевики',
  'adult': 'для взрослых',
  'adventures': 'приключения',
  'anime': 'аниме',
  'arthouse': 'арт-хаус',
  'biographical': 'биографические',
  'cognitive': 'познавательные',
  'comedy': 'комедии',
  'concert': 'концерт',
  'crime': 'криминал',
  'detective': 'детективы',
  'documentary': 'документальные',
  'drama': 'драмы',
  'ecchi': 'этти',
  'educational': 'образовательные',
  'erotic': 'эротика',
  'everyday': 'повседневность',
  'fairytale': 'сказки',
  'family': 'семейные',
  'fantasy': 'фэнтези',
  'fiction': 'фантастика',
  'fighting': 'боевые искусства',
  'foreign': 'зарубежные',
  'full-length': 'полнометражные',
  'historical': 'исторические',
  'horror': 'ужасы',
  'kids': 'детские',
  'kodomo': 'кодомо',
  'mahoushoujo': 'махо-сёдзё',
  'mecha': 'меха',
  'melodrama': 'мелодрамы',
  'military': 'военные',
  'multseries': 'мультсериалы',
  'musical': 'музыкальные',
  'musical': 'мюзиклы',
  'mystery': 'мистические',
  'parody': 'пародия',
  'realtv': 'реальное тв',
  'romance': 'романтические',
  'russian': 'русские',
  'samurai': 'самурайский боевик',
  'school': 'школа',
  'short': 'короткометражные',
  'shoujo': 'сёдзё',
  'shoujoai': 'сёдзё-ай',
  'shounen': 'сёнэн',
  'shounenai': 'сёнэн-ай',
  'soyzmyltfilm': 'советские',
  'sport': 'спортивные',
  'standup': 'стендап',
  'telecasts': 'телепередачи',
  'theatre': 'театр',
  'thriller': 'триллеры',
  'travel': 'путешествия',
  'ukrainian': 'украинские',
  'western': 'вестерны',
}

export const genres2 = {
  'вестерны': 'western',
  'семейные': 'family',
  'фэнтези': 'fantasy',
  'биографические': 'biographical',
  'арт-хаус': 'arthouse',
  'боевики': 'action',
  'военные': 'military',
  'детективы': 'detective',
  'криминал': 'crime',
  'приключения': 'adventures',
  'драмы': 'drama',
  'спортивные': 'sport',
  'фантастика': 'fiction',
  'комедии': 'comedy',
  'мелодрамы': 'melodrama',
  'триллеры': 'thriller',
  'ужасы': 'horror',
  'музыкальные': 'musical',
  'исторические': 'historical',
  'документальные': 'documentary',
  'эротика': 'erotic',
  'детские': 'kids',
  'путешествия': 'travel',
  'познавательные': 'cognitive',
  'театр': 'theatre',
  'концерт': 'concert',
  'стендап': 'standup',
  'короткометражные': 'short',
  'русские': 'russian',
  'украинские': 'ukrainian',
  'зарубежные': 'foreign',
  'реальное тв': 'realtv',
  'телепередачи': 'telecasts',
  'сказки': 'fairytale',
  'мюзиклы': 'musical',
  'аниме': 'anime',
  'для взрослых': 'adult',
  'мультсериалы': 'multseries',
  'полнометражные': 'full-length',
  'советские': 'soyzmyltfilm',
  'романтические': 'romance',
  'мистические': 'mystery',
  'боевые искусства': 'fighting',
  'самурайский боевик': 'samurai',
  'образовательные': 'educational',
  'повседневность': 'everyday',
  'пародия': 'parody',
  'школа': 'school',
  'кодомо': 'kodomo',
  'сёдзё-ай': 'shoujoai',
  'сёдзё': 'shoujo',
  'сёнэн': 'shounen',
  'сёнэн-ай': 'shounenai',
  'этти': 'ecchi',
  'махо-сёдзё': 'mahoushoujo',
  'меха': 'mecha',
}
 */
