// deno-fmt-ignore
export const CatalogType = {
  movie:   'films',
  series:  'series',
  anime:   'animation',
  cartoon: 'cartoons',
} as const

// deno-fmt-ignore
export const CatalogQueryType: Record<keyof typeof CatalogType, number> = {
  movie:   1,
  series:  2,
  cartoon: 3,
  anime:   82,
} as const

export const CatalogFilmGenres = [
  'action',
  'adventures',
  'arthouse',
  'biographical',
  'cognitive',
  'comedy',
  'concert',
  'crime',
  'detective',
  'documentary',
  'drama',
  'erotic',
  'family',
  'fantasy',
  'fiction',
  'foreign',
  'historical',
  'horror',
  'kids',
  'melodrama',
  'military',
  'musical',
  'musical',
  'russian',
  'short',
  'sport',
  'standup',
  'theatre',
  'thriller',
  'travel',
  'ukrainian',
  'western',
] as const

export const CatalogSeriesGenres = [
  'action',
  'adventures',
  'arthouse',
  'biographical',
  'comedy',
  'crime',
  'detective',
  'documentary',
  'drama',
  'erotic',
  'family',
  'fantasy',
  'fiction',
  'foreign',
  'historical',
  'horror',
  'melodrama',
  'military',
  'musical',
  'realtv',
  'russian',
  'sport',
  'standup',
  'telecasts',
  'thriller',
  'ukrainian',
  'western',
] as const

export const CatalogCartoonsGenres = [
  'action',
  'adult',
  'adventures',
  'anime',
  'arthouse',
  'biographical',
  'cognitive',
  'comedy',
  'crime',
  'detective',
  'documentary',
  'drama',
  'erotic',
  'fairytale',
  'family',
  'fantasy',
  'fiction',
  'foreign',
  'full-length',
  'historical',
  'horror',
  'kids',
  'melodrama',
  'military',
  'multseries',
  'musical',
  'russian',
  'short',
  'soyzmyltfilm',
  'sport',
  'thriller',
  'ukrainian',
  'western',
] as const

export const CatalogAnimationGenres = [
  'action',
  'adventures',
  'comedy',
  'detective',
  'drama',
  'ecchi',
  'educational',
  'erotic',
  'everyday',
  'fairytale',
  'fantasy',
  'fiction',
  'fighting',
  'historical',
  'horror',
  'kids',
  'kodomo',
  'mahoushoujo',
  'mecha',
  'military',
  'musical',
  'mystery',
  'parody',
  'romance',
  'samurai',
  'school',
  'shoujo',
  'shoujoai',
  'shounen',
  'shounenai',
  'sport',
  'thriller',
] as const
