name: CI

on:
  push:
  pull_request:
    branches: [main]
  workflow_call:
  workflow_dispatch:

jobs:
  check:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v4
      - uses: dprint/check@v2.3

      - name: Enable Corepack
        run: corepack enable

      - name: Use Node.js
        uses: actions/setup-node@v6
        with:
          node-version: latest
          cache: "pnpm"

      - name: Install dependencies
        run: pnpm install

      - name: Lint
        run: pnpm lint

      - name: Build
        run: pnpm build

      # - name: Set up Deno
      #   uses: denoland/setup-deno@v2
      #   with:
      #     cache: true

      # - name: Format
      #   run: deno fmt --check

      # - name: Test
      #   run: >
      #     deno test --parallel
      #     kv/
      #     openapi/
      #     web/
      #     webauthn/

      # - name: Publish dry run
      #   run: deno publish --allow-slow-types --dry-run
